### ISSUE TITLE
"Minting Failed. Please try again!" message shown every time but actually everything works

### ISSUE THREAD

**Issue by MahjongDogs** [Fulgurus/candy-machine-v2-responsive-ui#23]
"Minting Failed. Please try again!" message shown every time but actually everything works

Seems many people encounter the same issue. Any one find some solution to that? Thanks!

**Comment by ToluAgabi** [comment]
what

> "Minting Failed. Please try again!" message shown every time but actually everything works
> 
> Seems many people encounter the same issue. Any one find some solution to that? Thanks!

What is the exact error message on the console?

**Comment by fonko** [comment]
the error is empty
that is because it defines the error message but if the error cames empty it will set a generic Minting Failed. Please try again! which is not ideal

line 646 (approx) from Home.tsx

`    } catch (error: any) {
      console.log(JSON.stringify(error));
      **let message = error.msg || "Minting failed! Please try again!"**;`

**Comment by fonko** [comment]
so, after some digging i found that there is some problem with this code (check the image) I commented those line and we get confetti after all! 

![image](https://user-images.githubusercontent.com/2717577/175826822-6ac69223-8eac-468b-8a4f-b09932d34387.png)


not sure what is the actual issue here, some one pls investigate if there is some weird functionality after commenting this lines. 

i actually find that the functionality cycle works, got my NFT, got my confetti party success message and what is left is to imaginary sell my dummy nft and be dummy rich!

**Comment by fonko** [comment]
Same code in candy-machine will fix the fact that after the confetti it doesn't update in realtime the count of NFT minted
![image](https://user-images.githubusercontent.com/2717577/175827773-7c978087-c265-46bc-ac94-eb518c3f5477.png)

**Comment by Fulgurus** [comment]
@fonko Thanks for the update. Going to check that commented lines on my side. It may be the fix. I didn't understand if having them commented caused another issue with counter or not ?

**Comment by fonko** [comment]
having them commented worked for me, no issue found then. So great! thanks!!

**Comment by GottliebGlob** [comment]
Last commit have not fixed it. Just commented it out and everything works fine
